### ISSUE TITLE
Playlist TV series

### ISSUE THREAD

**Issue by albertinozz** [b-jesch/skin.estuary.modv2#26] opened 2021-12-28 16:17 UTC
I use to make playlists for TV series, anime series, cartoon series, and set them as widgets (eg “ongoing series” or “recently added series”).  
When I select the cover of the series from eidgets, nothing happens instead of opening the screen with the episodes or submenu with the various seasons.
Sorry for my bad english, i'm italian.

**Comment by b-jesch** [comment] 2021-12-28 22:31
> I use to make playlists for TV series, anime series, cartoon series, and set them as widgets (eg “ongoing series” or “recently added series”).

Could you describe in detail how do you create the playlists and set them as widgets (Home Menu?).

**Comment by albertinozz** [comment] 2021-12-29 10:19
Ok
In my hard drives I have several directories, each one contains a genre.
In Kodi I like to keep the main menu divided into genres, not just "movies" and "TV series". 
To do this, I create a smart playlist to use as a menu item (eg. “Anime”).
The rule for this playlist is:
path starts with [my_anime_folder].

![image](https://user-images.githubusercontent.com/96786691/147651418-9be4ccff-e681-47b5-8c18-553e58630501.jpeg)

Now I create another Smart playlist to use as a Widget (eg. "Anime recently added").
The rules for this playlist are:
1. Playlist is “anime”
2. order by date added 
3. order descending.

![image](https://user-images.githubusercontent.com/96786691/147651580-7c4ecfbc-84c8-4286-bdb8-f6a9a1eb0e41.jpeg)

Now I customize main menu.
I create a new "Anime" item.
I choose item for menu:
Video library> Playlist> Anime (my playlist)> Display.
Now I customize widgets: 
Set type of widgets> widgets to personalize> Lists (up to 8 items).  
I create my widget: 
select widget 1 > Video library> Playlist> Anime recently added> Display.  

![image](https://user-images.githubusercontent.com/96786691/147651716-ba59dc28-612d-41fe-83ed-b520652396a4.jpeg)

Now I have a fully functional "anime" menu.
The problem is in the widget showing me the cover of the recently added anime. It is not working.  
When I select a cover, nothing happens.

https://www.dropbox.com/s/zw7fd0oy4ffw7af/Video%2029-12-21%2C%2011%2006%2001.mov?dl=0

I hope I was as clear as possible.
Thanks for everything!

**Comment by b-jesch** [comment] 2021-12-29 15:06
Thank you for the detailed explanation. I'll try to recreate the behavior when I have a little more time.

**Comment by albertinozz** [comment] 2021-12-29 15:30
Great! I'll wait for your news...
I forgot to tell that with kodi 18 (leia) + estuary mod v2, I did not encounter this problem.
Thanks again for your great job!

**Comment by b-jesch** [comment] 2021-12-29 18:02
I can confirm the behavior. This only seems to occur when using the widget panel or widget list and displaying video content (and possibly audio content). Must dive deeper into this...

**Comment by albertinozz** [comment] 2021-12-29 19:44
That's right, it only occurs in the widgets section and only with tv series.   
I use the same process with movies (comedy, horror, action, etc.) with no problem.  
The only difference is that with the series, when I click on the poster, the selection of episodes must appear, unlike with the movies that when I click on the poster the playback starts

**Comment by b-jesch** [comment] 2022-01-01 20:35
Seems to be an issue with script.skinshortcuts: https://forum.kodi.tv/showthread.php?tid=366119&highlight=skinshortcuts

**Comment by albertinozz** [comment] 2022-01-02 09:15
Nice!
What i have to do to downgrade script.skinshortcuts to 1.1.5?
Sorry but i am semi-noob ^_^;

**Comment by b-jesch** [comment] 2022-01-02 09:25
Download the ZIP from the link above. Netxt: https://kodi.wiki/view/Add-on_manager#How_to_install_from_a_ZIP_file

Do not update automatically your addons, otherwise it will be overwritten with 2.0.0

**Comment by albertinozz** [comment] 2022-01-02 09:28
Ok, i download this file, and add-ons > install from .zip file?

**Comment by albertinozz** [comment] 2022-01-03 13:44
Thanks a lot b-jesch, all worked smoothly!

**Comment by b-jesch** [comment] 2022-01-03 17:47
Ok, I close the issue.

**Closed by b-jesch** 2022-01-03 17:47 UTC
