### ISSUE TITLE
After installing Kodi crashes immediately after it finished loading due to Embuary.helper and Embuary.helper tries to access private folders in /home

### ISSUE THREAD

**Issue by mYnDstrEAm** [b-jesch/skin.estuary.modv2#90] opened 2022-10-12 21:02 UTC
On Debian11 with Kodi 19.1 I installed the skin after installing the kodinerds repo. It asked me to also install Embuary Helper or something similar. Once it was installed I added a new option to the left sidebar and moved a few items there (which worked great and was useful for [this](https://forum.kodi.tv/showthread.php?tid=362894)). It then crashed (I don't think I quit it).

I then tried launching Kodi again but as soon as it finishes loading it crashes. With finishing loading I mean that it correctly displays Kodi and the Favorites page which I had opened before it quit and I can even switch pages (Movies, Series, ...) for almost one second. I'm using Kodi with firejail for security sandboxing which worked well with Kodi (command `firejail kodi`).

Here are the warnings in kodi.log after `load skin from: /home/username/.kodi/addons/skin.estuary.modv2/ (version: 3.4.2+matrix.5)`:

```
...
WARNING <general>: CApplication::Initialize - startup.xml taints init process
WARNING <general>: JSONRPC: Could not parse type "Setting.Details.SettingList"
...
WARNING <general>: Skin has invalid include: skinshortcuts-template-PersonalWidgetList
WARNING <general>: Skin has invalid include: skinshortcuts-template-PersonalWidgetPanel
WARNING <general>: Skin has invalid include: skinshortcuts-template-PersonalWidgetVariable
...
```

In the console it has this output:
```
...
Child process initialized in x ms
/usr/bin/kodi: 1: ulimit: error setting limit (Operation not permitted)
kodi: ulimit is unsupported by this shell
failed to open zone.tab
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
sh: 1: nmblookup: Permission denied
context.c:56: warning: mpd_setminalloc: ignoring request to set MPD_MINALLOC a second time

context.c:56: warning: mpd_setminalloc: ignoring request to set MPD_MINALLOC a second time

context.c:56: warning: mpd_setminalloc: ignoring request to set MPD_MINALLOC a second time

context.c:56: warning: mpd_setminalloc: ignoring request to set MPD_MINALLOC a second time

Segmentation fault
find: '/home/username/.folder': Permission denied
find: '/home/username/.folder2': Permission denied
find: '/home/username/.folder3': Permission denied
...
cat: /proc/sys/kernel/core_pattern: Permission denied
cat: /proc/sys/kernel/core_pattern: Permission denied
dirname: missing operand
Try 'dirname --help' for more information.
Crash report available at /home/username/kodi_crashlog-20221012_time.log

Parent is shutting down, bye...
```

I think the outputs until nmblookup are normal and I had them before, I think had these mpd_setminalloc warnings before too but iirc not always and not four. I don't think I had the remaining errors. It shouldn't try to access these folders, it's a reason why I'm using sandboxing.

**Comment by b-jesch** [comment] 2022-10-12 21:18
Warnings are not errors.

> WARNING <general>: Skin has invalid include: skinshortcuts-template-PersonalWidgetList
WARNING <general>: Skin has invalid include: skinshortcuts-template-PersonalWidgetPanel
WARNING <general>: Skin has invalid include: skinshortcuts-template-PersonalWidgetVariable

simply means that you don't have any self created widgets in use and therefore the templates of skinshortcuts will not used. You can ignore that.

The reason for crashing kodi (not the skin) ist the segmentation fault. Look into the crash report.

**Comment by mYnDstrEAm** [comment] 2022-10-12 21:27
There are no errors after the `load skin from` entry there either, only those same 5 warnings. There are errors only _before_ it loads the skin:
```
ERROR <general>: DBus error: org.freedesktop.DBus.Error.InvalidArgs - No such property “OnLowBattery”
ERROR <general>: DBus error: org.freedesktop.DBus.Error.InvalidArgs - No such property “CanSuspend”
ERROR <general>: DBus error: org.freedesktop.DBus.Error.InvalidArgs - No such property “CanHibernate”
```
I think these three errors are normal. Haven't enabled debug mode.

Also even it does work the skin should not try to access folders in the /home partition, Kodi didn't do that before installing the skin.

I think I press yes to a second prompt of installing an Embuary addon and it crashed afterwards, maybe it has something to do with that. Is there maybe a way to edit a config file to disable the newly installed addons and see if Kodi works then so one can at least find out the addon that's causing it. Otherwise, no idea why this segmentation fault occurs.

**Comment by C4Wiz** [comment] 2022-10-12 21:45
<https://kodi.wiki/view/Userdata>
Userdata - Official Kodi Wiki<https://kodi.wiki/view/Userdata>
kodi.wiki<https://kodi.wiki/view/Userdata>
[favicon.ico]<https://kodi.wiki/view/Userdata>

User settings, addons, etc. are indeed in your home dir.

David Smythe
Sent from my  iPhone 14 Pro Max on iOS 16

On Oct 12, 2022, at 4:27 PM, mYnDstrEAm ***@***.***> wrote:

﻿

There are no errors after the load skin from entry there either, only those same 5 warnings. There are errors only before it loads the skin:

ERROR <general>: DBus error: org.freedesktop.DBus.Error.InvalidArgs - No such property “OnLowBattery”
ERROR <general>: DBus error: org.freedesktop.DBus.Error.InvalidArgs - No such property “CanSuspend”
ERROR <general>: DBus error: org.freedesktop.DBus.Error.InvalidArgs - No such property “CanHibernate”


I think these three errors are normal. Haven't enabled debug mode.

Also even it does work the skin should not try to access folders in the /home partition, Kodi didn't do that before installing the skin.

I think I press yes to a second prompt of installing an Embuary addon and it crashed afterwards, maybe it has something to do with that. Is there maybe a way to edit a config file to disable the newly installed addons and see if Kodi works then so one can at least find out the addon that's causing it. Otherwise, no idea why this segmentation fault occurs.

**Comment by mYnDstrEAm** [comment] 2022-10-12 21:50
That's not really helpful. They are only in one specific folder in the home dir and Kodi never tried to access these folders previously. Please keep the message as short as possible. I'm first trying to find out the cause of the crashing and fix it and then worry about it trying to access these folders.

**Comment by C4Wiz** [comment] 2022-10-12 22:17
Reset kodi to defaults, see if it starts normally, install the skin, etc.

David Smythe
Sent from my  iPhone 14 Pro Max on iOS 16

On Oct 12, 2022, at 4:51 PM, mYnDstrEAm ***@***.***> wrote:

﻿

That's not really helpful. They are only in one specific folder in the home dir and Kodi never tried to access these folders previously. Please keep the message as short as possible. I'm first trying to find out the cause of the crashing and fix it and then worry about it trying to access these folders.

**Comment by mYnDstrEAm** [comment] 2022-10-12 22:21
I don't want to undo all the many settings I have done before. I asked `Is there maybe a way to edit a config file to disable the newly installed addons and see if Kodi works then so one can at least find out the addon that's causing it` which is what I would intend to do next.

**Comment by C4Wiz** [comment] 2022-10-12 23:59
Create a backup, then reset. Then install only the skin in question, if it doesn’t crash then it’s something else you installed. Then it’s a issue for the kodi forum!

This skin is pretty flawless,

David Smythe
Sent from my  iPhone 14 Pro Max on iOS 16

On Oct 12, 2022, at 5:21 PM, mYnDstrEAm ***@***.***> wrote:

﻿

I don't want to undo all the many settings I have done before. I asked Is there maybe a way to edit a config file to disable the newly installed addons and see if Kodi works then so one can at least find out the addon that's causing it which is what I would intend to do next.

**Comment by b-jesch** [comment] 2022-10-13 01:26
Kodi install and access all additional addons (even skin and helpers) in $HOME/.kodi/ . That's the normal behaviour. Only a fresh installation **without any addons** resides in /usr/share/kodi.

Note that Team kodi offers no support for an installation of Kodi from Debian. See installation notes here: https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux#Installing_Kodi_on_Ubuntu-based_distributions_with_Team_Kodi_PPA

As this issue does not concern the skin, I'm closing it. Please discuss in the appropiate forums of kodi.tv

Regards

**Closed by b-jesch** 2022-10-13 01:26 UTC

**Comment by mYnDstrEAm** [comment] 2022-10-13 09:18
>Create a backup, then reset. Then install only the skin in question, if it doesn’t crash then it’s something else you installed. Then it’s a issue for the kodi forum!

Already could restore it, as I wrote, by removing those two folders and then uninstalling the skin. So there's no need to restore a backup and reset all the many changes to Kodi settings that may have been done in the meantime. I only installed the skin in question as wrote as well. The skin asks me to install the Embuary addon. It's also an issue for the Embuary helper GitHub repo, not the forum, because that's what causing the crash.

>Kodi install and access all additional addons (even skin and helpers) in $HOME/.kodi/ . That's the normal behaviour. Only a fresh installation without any addons resides in /usr/share/kodi.

Sure but how is this relevant to anything I wrote?

How does this address the crash and that it tries to access all the hidden folders in /home/username/?

Kodi 19.1 is now in the Debian repos, I don't know how well supported that combination is with Kodi's core developers but I don't think it matters here.

>As this issue does not concern the skin, I'm closing it. Please discuss in the appropiate forums of kodi.tv

Wouldn't consider this issue closed but the problem is caused by the Embuary helper addon. I will file a bug report there (at its GitHub repo). If a dependency causes crashes (and tries to access personal files without a need for this like malware does), then I think it's also a problem of the software that uses the dependency, one alternative could be to not use that dependency or to switch it out for another one.

**Comment by mYnDstrEAm** [comment] 2022-10-13 09:24
Issue is now here: https://github.com/sualfred/script.embuary.helper/issues/67

**Comment by b-jesch** [comment] 2022-10-13 09:43
> Sure but how is this relevant to anything I wrote?
Here:
> Also even it does work the skin should not try to access folders in the /home partition, Kodi didn't do that before installing the skin.

The Embuary Helper is essential for the skin. Without the helper you lost a lot of functionality.

**Comment by b-jesch** [comment] 2022-10-13 09:55
And again: $HOME/.kodi is not a private folder, this is a hidden folder and contains almost all installed addons of the current installation, the config of all addons + the config of Kodi itself (.kodi/userdata), the Video/Audio databases (.kodi/userdata/Databases) and more...

**Comment by b-jesch** [comment] 2022-10-13 11:36
For now You are the first with such an issue. Note, Kodi 19.1 is quite old - the actual version is 19.5. Nobody runs Kodi in a sandbox and there is no official support for a Debian-Kodi from Team Kodi. On other side there are reported issues with some Python versions used in Debian which caused Kodi to crash. Not a skin problem.

Google for "Debian kodi python crash" (without ").

**Comment by mYnDstrEAm** [comment] 2022-10-13 11:42
Just to add: there are many who run Kodi with firejail, it has its [own profile](https://github.com/netblue30/firejail/blob/master/etc/profile-a-l/kodi.profile) which ships with firejail. Without firejail I wouldn't have noticed the issue about it trying to access these folders and it may also be involved in what's causing the crash. Didn't have Kodi python crashes so far. Not a problem of the skin, but probably of one of its dependencies.

**Comment by b-jesch** [comment] 2022-10-13 11:49
> Not a problem of the skin, but probably of one of its dependencies.

Yes, but this is not on my site. You have done the right way to inform the maintainer of the helper addon. Meanwhile we have to wait for an answer...

You can remove the dependency from the helper addon in the addon.xml of the skin, but don't wonder if the skin has only limited functionality.
