### ISSUE TITLE
Use Simple seekbar on chapter and time seeking issues

### ISSUE THREAD

**Issue by C4Wiz** [b-jesch/skin.estuary.modv2#99] opened 2022-12-01 18:57 UTC
there is no seekbar on trailers
seek during a movie does not use simple seek bar

**Comment by C4Wiz** [comment] 2022-12-02 13:23
> > seek during a movie does not use simple seek bar
> 
> Can't confirm this.

so this works correctly for you?

**Comment by b-jesch** [comment] 2022-12-02 14:43
While playing a movie cursor keys (left/right/up/down) opens the seekbar and you can jump chapterwise (up/down) or in the defined time intervals. This is the expected behaviour for me.

If video OSD is open, it's possible to select the seekbar (key up) and navigate then in defined time intervals (left/right) or mouse pointer. This also fixes an issue reported here: https://forum.kodi.tv/showthread.php?tid=366400&pid=3114844#pid3114844

**Comment by C4Wiz** [comment] 2022-12-02 16:24
oh, ok. i am using a home automation remote with ip control, using ff,rew,prev,next buttions

**Comment by C4Wiz** [comment] 2022-12-04 14:38
can these be added?

**Comment by b-jesch** [comment] 2022-12-04 16:44
Nope. FF, Rew, Prev, Next are already part of the video/audio OSD. Alternatively your buttons on remote should do this job. If your buttons on remote doesn't execute the expected function you have to map them properly in Lircmap.xml or using the keymap editor addon for doing this.

**Comment by C4Wiz** [comment] 2022-12-04 16:47
buttons work fine but the full seekbar is activated, not the simple seek bar

**Comment by b-jesch** [comment] 2022-12-04 17:06
There is an option for this: Video OSD: Use simple Seekbar on chapter and Time seeking.

Option disabled (full seekbar):

![Bildschirmfoto von 2022-12-04 18-01-26](https://user-images.githubusercontent.com/10152384/205504875-c0ee0915-1136-4201-897c-a8d80204d71d.png)

Option enabled (simple seekbar):

![Bildschirmfoto von 2022-12-04 18-02-19](https://user-images.githubusercontent.com/10152384/205504899-509e9ad5-2280-4c6e-8ae9-776566c820e1.png)

**Comment by C4Wiz** [comment] 2022-12-04 17:12
Like i said option is enabled but ff, rew during a movie does not use simple seek bar

**Comment by b-jesch** [comment] 2022-12-04 17:31
This isn't true. As I'm not own a remote control with ff/rew buttons, I'm using the 'R' and 'F' keys on keyboard: https://kodi.wiki/view/Keyboard_controls. Both they show the seekbar while playing a movie and pressing 'R' or 'F'.

![Bildschirmfoto von 2022-12-04 18-22-46](https://user-images.githubusercontent.com/10152384/205505869-314348ad-0726-48ef-b72c-2e6421bfbd56.png)

![Bildschirmfoto von 2022-12-04 18-23-06](https://user-images.githubusercontent.com/10152384/205505877-76d8a98c-f1e6-4a84-9ba4-c24b43c4ce0e.png)

Since I am sure this skin hasn't a bug, I will close the issue. The navigation here works as expected.

**Closed by b-jesch** 2022-12-04 17:31 UTC

**Comment by b-jesch** [comment] 2022-12-06 18:50
Ok, there was indeed an incorrectly resolved condition, when 'use small OSD' was not set. Has been fixed now. Available with next update. Enable 'use small OSD' until then.

**Comment by C4Wiz** [comment] 2022-12-07 18:16
> Ok, there was indeed an incorrectly resolved condition, when 'use small OSD' was not set. Has been fixed now. Available with next update. Enable 'use small OSD' until then.

Thank you for not giving up on this! i can confirm the issue is fixed

**Comment by b-jesch** [comment] 2022-12-08 08:30
That's not the right solution yet. The complete OSD doesn't show anymore for now. Have to investigate more time.
